### PR TITLE
PHOENIX-4664 Time Python driver tests failing

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
This requires uncommitted Phoenix side changes.

**Comment by stoty** [comment]
This requires unreleased Phoenix side changes.

**Comment by richardantal** [comment]
I ran the tests locally with python 3.12 and I got this error in test_timestamp:

```
E           AssertionError: Lists differ: [[1, [93 chars]12, 12, 1, 2)], [4, datetime.datetime(2015, 7,[30 chars]one]] != [[1, [93 chars]12, 13, 1, 2)], [4, datetime.datetime(2015, 7,[30 chars]one]]
E
E           First differing element 2:
E           [3, datetime.datetime(2015, 7, 12, 12, 1, 2)]
E           [3, datetime.datetime(2015, 7, 12, 13, 1, 2)]
E
E             [[1, datetime.datetime(2015, 7, 12, 13, 1, 2, 123000)],
E              [2, None],
E           -  [3, datetime.datetime(2015, 7, 12, 12, 1, 2)],
E           ?                                      ^
E
E           +  [3, datetime.datetime(2015, 7, 12, 13, 1, 2)],
E           ?                                      ^
E
E           -  [4, datetime.datetime(2015, 7, 12, 12, 1, 2, 123000)],
E           ?                                        ------
E
E           +  [4, datetime.datetime(2015, 7, 12, 13, 1, 2, 123000)],
E           ?                                      ++++++
E
E              [5, None]]

phoenixdb/tests/test_types.py:218: AssertionError
```

**Comment by stoty** [comment]
Thank you, it should be fixed with the new commit.

**Review by richardantal — APPROVED** [review]
LGTM

**Comment by stoty** [comment]
merged manually

**Pull request closed without merging**
