### PR TITLE
PHOENIX-5234 Create patch scripts for phoenix-connectors and phoenix-queryserver projects

### PR DESCRIPTION
**Pull request by nsgupta1**
This github workflow adds a check to run phoenix-connectors integration test based on every PR and push to master branch. Authors/reviewers can view the result of it in "check" tab of PR. @vincentpoon @ChinmaySKulkarni @twdsilva can you please look into this ?

### CODE REVIEW

**Comment by nsgupta1** [comment]
Removed on push action as requested.

**Comment by ChinmaySKulkarni** [comment]
lgtm @nsgupta1 Please squash all commits into 1 before we merge. Thanks

**Comment by stoty** [comment]
This has already been merged. The PR can be closed.

**Comment by stoty** [comment]
This has already been merged, closing.

**Pull request closed without merging**
