### PR TITLE
PHOENIX-5421: Phoenix Query server tests race condition issue on creating keytab folder

### PR DESCRIPTION
**Pull request by m2je**
…ting keytab folder

### CODE REVIEW

**Comment by swaroopak** [comment]
Can you please provide a back Port patch for your 2 PRs for 4.14 branch. Thanks!

**Comment by swaroopak** [comment]
When I ran the test without this PR, I got the following exception. I am unclear how this would fix it? Do I need to setup some configs?

`Caused by: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Illegal principal name s.kadam@INTERNAL.SALESFORCE.COM: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to s.kadam@INTERNAL.SALESFORCE.COM
	at org.apache.hadoop.security.UserGroupInformation$HadoopLoginModule.commit(UserGroupInformation.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at `

**Comment by m2je** [comment]
Not sure if I have seen this issue or could be related.
If the test could possibly run into the race condition explained on the ticket this may help prevent it.
 I would start with checking if the keytab file is as properly configured and exists on the path when test wants to use it.

**Comment by m2je** [comment]
> When I ran the test without this PR, I got the following exception. I am unclear how this would fix it? Do I need to setup some configs?
> 
> `Caused by: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Illegal principal name s.kadam@INTERNAL.SALESFORCE.COM: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to s.kadam@INTERNAL.SALESFORCE.COM at org.apache.hadoop.security.UserGroupInformation$HadoopLoginModule.commit(UserGroupInformation.java:200) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) at `

Not sure if I have seen this issue or it could be related.
If the test could possibly run into the race condition explained on the ticket this may help prevent it.
 I would start with checking if the keytab file is as properly configured and exists on the path when test wants to use it.

**Comment by swaroopak** [comment]
Thanks. Please don't forget to provide the patches for 4.14 for both your commits here. Thanks.

**Comment by swaroopak** [comment]
I am still seeing this issue. It has to do with AbstractKerborisedTest. thats being added in the previous commit. Is the test passing on your environment?

**Comment by m2je** [comment]
> Thanks. Please don't forget to provide the patches for 4.14 for both your commits here. Thanks.

I have already submitted the patches. For 4.14 branch my patch include this fix and back porting the test both (Please see my comment on the ticket).

**Comment by m2je** [comment]
> I am still seeing this issue. It has to do with AbstractKerborisedTest. thats being added in the previous commit. Is the test passing on your environment?

Yes, It passed on my local. If you are still talking the error you reported before that doesn't seem related. Otherwise please provide a full stack tract of the test that's failing and the branch /Hbase/ Phoenix version.
I would suggest to run tests multiple times to see if there are any race conditions.

**Comment by swaroopak** [comment]
There has to be something specific to your env, because tests are failing in 4.14 and this repo.

**Pull request closed without merging**
