### PR TITLE
PHOENIX-5873 Fix loadbalancer packaging problem for queryserver scripts

### PR DESCRIPTION
**Pull request by infraio**

### CODE REVIEW

**Comment by infraio** [comment]
@stoty Any comments?

**Comment by stoty** [comment]
It looks solid, but doesn't address every improvement that I have in mind for this ticket.
Could you make a different JIRA, say "Fix loadbalancer packaging" for it, and rename the patch ?

**Comment by joshelser** [comment]
Looks fine to me -- also, would echo what Istvan already said about fixing the description here to be more accurate after the other changes which have been done.

Can do those on commit if you'd prefer, @infraio

**Comment by stoty** [comment]
I'd like a new JIRA, not just a description, because there are still more problems that I've enumerated in this JIRA, and I'd prefer not to "use up" this JIRA on the loadbalancer fixes.

**Comment by joshelser** [comment]
> I'd like a new JIRA, not just a description, because there are still more problems that I've enumerated in this JIRA

OK, you got it Istvan. Sorry for making you come back here again and requesting what you wanted again.

**Comment by joshelser** [comment]
Looks like this has landed. Good to close, @stoty?

**Comment by stoty** [comment]
Sure.

**Comment by stoty** [comment]
Committed.

**Pull request closed without merging**
